2020-04-25 00:28:45,627 ERROR: Exception on /catalogue [GET] [in c:\users\simon\documents\code\python\flask_projects\graines\venv\lib\site-packages\flask\app.py:1892]
Traceback (most recent call last):
  File "c:\users\simon\documents\code\python\flask_projects\graines\venv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\simon\documents\code\python\flask_projects\graines\venv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\simon\documents\code\python\flask_projects\graines\venv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\simon\documents\code\python\flask_projects\graines\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\simon\documents\code\python\flask_projects\graines\venv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\simon\documents\code\python\flask_projects\graines\venv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\simon\documents\code\python\flask_projects\graines\venv\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\simon\Documents\Code\Python\Flask_projects\Graines\app\routes.py", line 58, in catalogue
    return render_template('plants.html', title='Catalogue', plants=plants, image_path=image_path, form=form)
  File "c:\users\simon\documents\code\python\flask_projects\graines\venv\lib\site-packages\flask\templating.py", line 140, in render_template
    ctx.app,
  File "c:\users\simon\documents\code\python\flask_projects\graines\venv\lib\site-packages\flask\templating.py", line 120, in _render
    rv = template.render(context)
  File "c:\users\simon\documents\code\python\flask_projects\graines\venv\lib\site-packages\jinja2\environment.py", line 1090, in render
    self.environment.handle_exception()
  File "c:\users\simon\documents\code\python\flask_projects\graines\venv\lib\site-packages\jinja2\environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "c:\users\simon\documents\code\python\flask_projects\graines\venv\lib\site-packages\jinja2\_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\simon\Documents\Code\Python\Flask_projects\Graines\app\templates\plants.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "C:\Users\simon\Documents\Code\Python\Flask_projects\Graines\app\templates\base.html", line 44, in top-level template code
    {% block content %}{% endblock %}
  File "C:\Users\simon\Documents\Code\Python\Flask_projects\Graines\app\templates\plants.html", line 33, in block "content"
    {{ form.submit() }}
jinja2.exceptions.UndefinedError: 'app.forms.PlantButtons object' has no attribute 'submit'
2020-04-25 00:28:59,559 INFO: Graines startup [in C:\Users\simon\Documents\Code\Python\Flask_projects\Graines\app\__init__.py:43]
2020-04-25 00:29:43,841 INFO: Graines startup [in C:\Users\simon\Documents\Code\Python\Flask_projects\Graines\app\__init__.py:43]
2020-04-25 00:34:15,306 INFO: Graines startup [in C:\Users\simon\Documents\Code\Python\Flask_projects\Graines\app\__init__.py:43]
2020-04-25 11:32:15,253 INFO: Graines startup [in C:\Users\simon\Documents\Code\Python\Flask_projects\Graines\app\__init__.py:43]
2020-04-25 11:35:08,756 INFO: Graines startup [in C:\Users\simon\Documents\Code\Python\Flask_projects\Graines\app\__init__.py:43]
2020-04-25 11:35:54,942 INFO: Graines startup [in C:\Users\simon\Documents\Code\Python\Flask_projects\Graines\app\__init__.py:43]
2020-04-25 11:44:10,139 INFO: Graines startup [in C:\Users\simon\Documents\Code\Python\Flask_projects\Graines\app\__init__.py:43]
2020-04-25 11:49:35,107 INFO: Graines startup [in C:\Users\simon\Documents\Code\Python\Flask_projects\Graines\app\__init__.py:43]
